# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao_VTciYWGIpsMvmWDOx6WbslJaChPH3
"""

def Mean ():
    counter = 0
    sum = 0
    while i != 1000:
      i=int(input())
      sum += 1
      counter += 1
    return (sum-1000)/(counter-1)