# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao_VTciYWGIpsMvmWDOx6WbslJaChPH3
"""

class students:
    def init(self,id,name):
        self.id=id
        self.name=name
    def __del__(self) :
       pass
    def mean(self):
        input ()


        return sum/vs
    def is_mashroot(self):
        if self.mean()<12:
            return True
        else:
            return false
    def str(self):
        print ("this class is student" )