# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao_VTciYWGIpsMvmWDOx6WbslJaChPH3
"""

class person:
    name=None
    score=100
    def say_hello(self):
     print("hello",self.name,"yuor score is",self.score)
h=person()
h.name="hasan"
h.score=56
h.say_hello()